-- Dosya: QuestTranslator_GossipData.lua
-- Sadece Gossip (Sohbet) çevirilerini içerir

QuestTranslator_GossipData = {
    ["I know, I know, I'm out here in the middle of nowhere!\n\nMy home is actually in Ratchet, but after crashing my zeppelin here, I thought I might as well start the research I came here to do!"] = "Biliyorum, biliyorum, kuş uçmaz kervan geçmez bir yerdeyim!\n\nEvim aslında Dişliçark'ta, ama zeplinimi buraya düşürdükten sonra, buraya yapmaya geldiğim araştırmaya başlamanın iyi bir fikir olabileceğini düşündüm!",
    ["Ah a visitor! Must be an adventurer, we don't get many tourists down this way. Grab a chair and a drink, make yourself comfortable. Say, you look like you have some meat on your bones. You thinkin about competing in the cage matches?"] = "Ah, bir ziyaretçi! Bir maceracı olmalı, buralara pek turist uğramaz. Bir sandalye çek, bir şeyler iç ve rahatına bak. Cılız da değilsin hani. Kafes dövüşlerinde yarışmayı düşünür müsün?",
    ["It's a miracle I made it here in one piece, buddy. I'm tellin' ya, the desert is out to get ya, ALL THE TIME!"] = "Tek parça hâlinde buraya gelebilmem adeta bir mucize, dostum. Sana söylüyorum, çöl seni yok etmek için can atıyor, HER AN!",
    ["We may have been suffering a drought but there's no shortage of meat! Care to browse my goods?"] = "Kuraklık çekiyor olabiliriz ama et kıtlığı yaşadığımız söylenemez! Mallarıma göz atmak ister misin?",
    ["Living out here in the desert is rough! I get so thirsty standing outside in this heat."] = "Çölün ortasında yaşamak çok zor! Bu sıcakta dışarıda dikilmekten içim kuruyor.",
    ["Welcome to Tanaris, Barbar. How can I be of service to you today? You don't look like a blacksmith to me, but I know how looks can be deceiving."] = "Tanaris'e hoş geldin, Barbar. Bugün sana nasıl yardımcı olabilirim? Bana pek demirci gibi görünmüyorsun, ama dış görünüşün nasıl aldatıcı olabileceğini iyi bilirim.",
    ["Sul'thraze... the first time I heard the word uttered I was around your age. It meant nothing to me then, as it means nothing to you now. It was not until a warband of trolls coming from Zul'Farrak laid waste to the land that I understood... and feared.\n\nMany will tell you that the Splitblade of Suffering does not exist. That it's a myth; a rumor started to scare children 'straight.' But believe me, human, it exists.\n\n<Trenton loses focus as he runs his hand across the jagged scar on his face.>"] = "Sul'thraze... Bu kelimeyi ilk duyduğumda senin yaşlarındaydın. O zamanlar benim için ne ifade ediyorsa, şu an senin için de hiçbir şey ifade etmiyor. Zul'Farrak'tan gelen bir trol savaş birliği toprakları kasıp kavurana kadar anlamamıştım... ve korkmamıştım.\n\nBirçoğu sana Acının Bölünmüş Kılıcı'nın var olmadığını söyleyecektir. Bunun bir efsane olduğunu; çocukları korkutup yola getirmek için çıkarılmış bir söylenti olduğunu. Ama bana inan, YOUR_RACE, o var.\n\n<Trenton, yüzündeki girintili çıkıntılı yara izinde gezdirirken dikkati dağılır.>",
    ["Hey, citizen! You look like a stout one. We guards are spread a little thin out here, and I could use your help..."] = "Hey, vatandaş! Yapılı birine benziyorsun. Buralarda muhafızlar olarak biraz az sayıdayız ve yardımına ihtiyacım var...",
    ["Stormwind is the pillar of the human race, maintained through strength of will and the edge of a sturdy blade."] = "Fırtınayeli, irade gücü ve sağlam bir bıçağın keskinliğiyle ayakta tutulan insan ırkının sütunudur.",
    ["May the Light protect you this day."] = "Işık bugün seni korusun.",
    ["Hey, come over here, and be quiet!"] = "Hey, buraya gel ve sessiz ol!",
    ["Well, now that you mention it, yeah, I did see something I thought was a little strange yesterday afternoon!\n\nI was running past some old troll ruins southeast of here; well, I wasn't really running, more like hopping... The sand's so hot!\n\nAnyway, so I was hopping past the ruins, when I noticed a camp set up there. Seems like a funny place to set up camp, if you ask me... I would have poked around a little more but one of those crazy big vultures chased me off."] = "Şimdi sen söyleyince aklıma geldi, evet, dün öğleden sonra biraz tuhaf olduğunu düşündüğüm bir şey gördüm!\n\nBuranın güneydoğusundaki eski trol harabelerinin yanından koşarak geçiyordum; yani pek koşuyor sayılmazdım, daha çok zıplıyordum... Kumlar o kadar sıcak ki!\n\nHer neyse, harabelerin yanından zıplayarak geçerken orada kurulmuş bir kamp fark ettim. Bana sorarsan kamp kurmak için tuhaf bir yer... Biraz daha etrafa bakınacaktım ama o çılgın büyük akbabalardan biri beni kovaladı.",
}