-- Dosya: QuestTranslator_GossipData.lua
-- Sadece Gossip (Sohbet) çevirilerini içerir

QuestTranslator_GossipData = {
    ["I know, I know, I'm out here in the middle of nowhere!\n\nMy home is actually in Ratchet, but after crashing my zeppelin here, I thought I might as well start the research I came here to do!"] = "Biliyorum, biliyorum, kuş uçmaz kervan geçmez bir yerdeyim!\n\nEvim aslında Dişliçark'ta, ama zeplinimi buraya düşürdükten sonra, buraya yapmaya geldiğim araştırmaya başlamanın iyi bir fikir olabileceğini düşündüm!",
    ["Ah a visitor! Must be an adventurer, we don't get many tourists down this way. Grab a chair and a drink, make yourself comfortable. Say, you look like you have some meat on your bones. You thinkin about competing in the cage matches?"] = "Ah, bir ziyaretçi! Bir maceracı olmalı, buralara pek turist uğramaz. Bir sandalye çek, bir şeyler iç ve rahatına bak. Cılız da değilsin hani. Kafes dövüşlerinde yarışmayı düşünür müsün?",
    ["It's a miracle I made it here in one piece, buddy. I'm tellin' ya, the desert is out to get ya, ALL THE TIME!"] = "Tek parça hâlinde buraya gelebilmem adeta bir mucize, dostum. Sana söylüyorum, çöl seni yok etmek için can atıyor, HER AN!",
    ["We may have been suffering a drought but there's no shortage of meat! Care to browse my goods?"] = "Kuraklık çekiyor olabiliriz ama et kıtlığı yaşadığımız söylenemez! Mallarıma göz atmak ister misin?",
    ["Living out here in the desert is rough! I get so thirsty standing outside in this heat."] = "Çölün ortasında yaşamak çok zor! Bu sıcakta dışarıda dikilmekten içim kuruyor.",
    ["Welcome to Tanaris, Barbar. How can I be of service to you today? You don't look like a blacksmith to me, but I know how looks can be deceiving."] = "Tanaris'e hoş geldin, Barbar. Bugün sana nasıl yardımcı olabilirim? Bana pek demirci gibi görünmüyorsun, ama dış görünüşün nasıl aldatıcı olabileceğini iyi bilirim.",
    ["Sul'thraze... the first time I heard the word uttered I was around your age. It meant nothing to me then, as it means nothing to you now. It was not until a warband of trolls coming from Zul'Farrak laid waste to the land that I understood... and feared.\n\nMany will tell you that the Splitblade of Suffering does not exist. That it's a myth; a rumor started to scare children 'straight.' But believe me, human, it exists.\n\n<Trenton loses focus as he runs his hand across the jagged scar on his face.>"] = "Sul'thraze... Bu kelimeyi ilk duyduğumda senin yaşlarındaydın. O zamanlar benim için ne ifade ediyorsa, şu an senin için de hiçbir şey ifade etmiyor. Zul'Farrak'tan gelen bir trol savaş birliği toprakları kasıp kavurana kadar anlamamıştım... ve korkmamıştım.\n\nBirçoğu sana Acının Bölünmüş Kılıcı'nın var olmadığını söyleyecektir. Bunun bir efsane olduğunu; çocukları korkutup yola getirmek için çıkarılmış bir söylenti olduğunu. Ama bana inan, YOUR_RACE, o var.\n\n<Trenton, yüzündeki girintili çıkıntılı yara izinde gezdirirken dikkati dağılır.>",
    ["Hey, citizen! You look like a stout one. We guards are spread a little thin out here, and I could use your help..."] = "Hey, vatandaş! Yapılı birine benziyorsun. Buralarda muhafızlar olarak biraz az sayıdayız ve yardımına ihtiyacım var...",
    ["Stormwind is the pillar of the human race, maintained through strength of will and the edge of a sturdy blade."] = "Fırtınayeli, irade gücü ve sağlam bir bıçağın keskinliğiyle ayakta tutulan insan ırkının sütunudur.",
    ["May the Light protect you this day."] = "Işık bugün seni korusun.",
    ["Hey, come over here, and be quiet!"] = "Hey, buraya gel ve sessiz ol!",
    ["Well, now that you mention it, yeah, I did see something I thought was a little strange yesterday afternoon!\n\nI was running past some old troll ruins southeast of here; well, I wasn't really running, more like hopping... The sand's so hot!\n\nAnyway, so I was hopping past the ruins, when I noticed a camp set up there. Seems like a funny place to set up camp, if you ask me... I would have poked around a little more but one of those crazy big vultures chased me off."] = "Şimdi sen söyleyince aklıma geldi, evet, dün öğleden sonra biraz tuhaf olduğunu düşündüğüm bir şey gördüm!\n\nBuranın güneydoğusundaki eski trol harabelerinin yanından koşarak geçiyordum; yani pek koşuyor sayılmazdım, daha çok zıplıyordum... Kumlar o kadar sıcak ki!\n\nHer neyse, harabelerin yanından zıplayarak geçerken orada kurulmuş bir kamp fark ettim. Bana sorarsan kamp kurmak için tuhaf bir yer... Biraz daha etrafa bakınacaktım ama o çılgın büyük akbabalardan biri beni kovaladı.",
    ["De sands be cruel and without compromise. Perfect ground for training."] = "Kumlar zalimdir ve asla taviz vermez. Antrenman yapmak için kusursuz bir zemin.",
    ["With some of the technology that was recovered by bold gnomes venturing into Gnomeregan, I have managed to construct my greatest invention: The Matter Transporter! All I need now is a skilled Gnomish Engineer to build a powerful beacon attuned to the transporter."] = "Gnomeregan'a giren cesur cüceler [gnome] tarafından kurtarılan bazı teknolojilerle birlikte, en büyük icatımı inşa etmeyi başardım: Madde Işınlayıcısı! Şimdi tek ihtiyacım olan, ışınlayıcıya uyarlanmış güçlü bir işaret fişeği inşa edecek yetenekli bir Cüce [Gnomish] Mühendisi.",
    ["Hi there! I have a proposition for an adventure-seeker such as you, if you are up to the challenge!\n\nAlong with my invention, the Super Egg-O-Matic, I am hard at work aiding the druids with their campaign to save the hippogryphs. The birds are being affected by the evil effects of the Gordunni ogres inhabiting the ruins of Feralas, and their numbers are dwindling.\n\nI collect many different types of eggs. Will you help and find some for me?"] = "Selam! Eğer bu maceraya hazırsan, senin gibi bir macera arayışındakine bir teklifim var!\n\nHarika icadım Süper Yumurtamatik ile birlikte, druidlerin hipogrifleri kurtarma kampanyasına yardım etmek için var gücümle çalışıyorum. Feralas [Feralas] harabelerinde yaşayan Gordunni ogrelerinin kötü etkileri kuşları vuruyor ve sayıları giderek azalıyor.\n\nBirçok farklı türde yumurta topluyorum. Bana yardım edip biraz bulabilir misin?",
    ["You are currently undergoing a hardcore challenge and cannot access guild banks."] = "Şu anda bir zorlu mod [hardcore] mücadelesindesin ve lonca bankalarına [guild bank] erişemezsin.",
    ["In a place called Feralas to the west of here, the hippogryphs, long-time companions of the night elves, are in danger.\n\nI need you to rescue an egg from the ruins of Isildien, to the south, there. The Super Egg-O-Matic can analyze any egg brought to it and judge if it is likely to hatch. I then send the eggs along to the druids, safe from the Gordunni ogres' dark magics.\n\nPlease know, Barbar, some of the rescued eggs are bad eggs, and will never hatch."] = "Buranın batısında Feralas [Feralas] adında bir yerde, gece elflerinin [night elf] uzun süredir yoldaşı olan hipogrifler tehlikede.\n\nGüneydeki Isildien [Isildien] harabelerinden bir yumurta kurtarmanı istiyorum. Süper Yumurtamatik [Super Egg-O-Matic], kendisine getirilen herhangi bir yumurtayı analiz edebilir ve kuluçkadan çıkma olasılığını değerlendirebilir. Ardından yumurtaları Gordunni ogre'larının [ogre] kara büyülerinden uzak, güvenli bir şekilde druidlere gönderiyorum.\n\nŞunu bil ki Barbar, kurtarılan yumurtaların bazıları bozuk yumurtalardır ve asla kuluçkadan çıkmayacaklardır.",
    ["I've been working on a way to transport oil underground between major cities, but everyone tells me it's a pipe dream."] = "Büyük şehirler arasında yeraltından petrol taşımanın bir yolu üzerinde çalışıyorum, ancak herkes bunun gerçekleşmesi imkansız bir hayal olduğunu söylüyor.",
    ["Greetings, YOUR_CLASS. I pity your kind, for the secrets of true magic are beyond you..."] = "Selamlar, YOUR_CLASS. Türünüze acıyorum, çünkü gerçek büyünün sırları sizin kavrayışınızın ötesinde...",
    ["May the spirits be with you."] = "Ruhlar seninle olsun.",
    ["You be watchin' yerself, YOUR_CLASS. Respect our ways, or a curse be on you and yours."] = "Kendine dikkat et, YOUR_CLASS. Tarzımıza saygı duy, yoksa lanet senin ve sevdiklerinin üzerine olsun.",
    ["The Valley of Trials will temper even the weakest into a warrior worthy to join the Horde. Those who cannot rise to its tests will be left to bake in the scorching desert sun."] = "İmtihan Vadisi [The Valley of Trials], en zayıfları bile Horde'a katılmaya layık bir savaşçıya dönüştürecektir. Sınavlarının üstesinden gelemeyenler ise kavurucu çöl güneşinde kavrulmaya mahkum edilecektir.",
    ["What kin I do for ya, mon?"] = "Ne yapabilirim senin için, dostum?",
    ["I don't train your kind YOUR_CLASS. Find your own trainer before you anger me."] = "Senin gibileri eğitmiyorum YOUR_CLASS. Beni öfkelendirmeden önce kendi eğitmenini bul.",
    ["What a weird place, mon. I much prefer wall of Zul'Aman to... this.\n\nIf ya be needing training, I be here."] = "Ne tuhaf bir yer, dostum. Zul'Aman surlarını şuraya tercih ederim...\n\nEğer eğitime ihtiyacın olursa, buradayım.",
    ["Your will is not strong enough to manipulate the forces we control, hunter."] = "İradeniz, kontrol ettiğimiz güçleri manipüle etmeye yetmez avcı.",

}

QuestTranslator_OptionData = {
    ["Seen any strange things in the desert lately?"] = "Son zamanlarda çölde garip bir şeyler gördün mü?",
    ["Please tell me more about the Gordunni ogres."] = "Lütfen bana Gordunni ogre'ları [ogre] hakkında daha fazla bilgi ver.",
    ["Please tell me more about the hippogryphs."] = "Lütfen bana hipogrifler hakkında daha fazla bilgi ver.",
}